DROP PROCEDURE RTHOMPSON1/EXAMPLE1;
CREATE PROCEDURE RTHOMPSON1/EXAMPLE1  (
 IN  p_InParm       CHAR(20),
 OUT p_OutParm      CHAR(200))
  LANGUAGE RPGLE
 SPECIFIC RTHOMPSON1/EXAMPLE1
 NOT DETERMINISTIC
 CALLED ON NULL INPUT
 EXTERNAL NAME RTHOMPSON1/EXAMPLE1
 PARAMETER STYLE SQL ;
